steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/build:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './build-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/build',
#      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/build:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/build',
      'steamwheedle-cartel/run-compute-pricelist-histories/build'
    ]

#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './runtime-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime',
#      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta', 'run', 'deploy',
      'run-compute-pricelist-histories',
      '--image', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--timeout', '120s',
      '--concurrency', '200'
    ]
images: [
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/build:latest',
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-compute-pricelist-histories/runtime:latest'
]
